FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
        cmake \
        clang \
        build-essential \
        libsdl2-dev \
        libglew-dev \
        libgl1-mesa-dev \
        pkg-config \
        glew-utils && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jenkins

