version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.local'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost/'
    ports:
      - '8080:80'   
      - '2222:22'    
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - ci_net

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: always
    user: root
    hostname: 'jenkins.local'
    ports:
      - '8081:8080' 
      - '50000:50000'
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"         
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - gitlab
      - jenkins
    networks:
      - ci_net 

networks:
  ci_net:
    driver: bridge

